### ISSUE TITLE
Turn on and off without setting brightness

### ISSUE THREAD

**Issue by Xento** [davidgraeff/Openhab2-milight2#2]
It would be nice if it would be possible to turn the lights on and off without changing the bringtness.
For example when I turn them on ad change the brightness with a remote, the next time I turn them on, i want them to have the same brightness as they had when I turned them off.

**Comment by davidgraeff** [comment]
Hey, could u please open a bug report on the official openhab2 add-on repository? This one here is temporary only. But yeah I'll have a look later
